export const bodyFields = [
    //Character
    "Gender",
    "Remove Bracelet",
    "God",
    "Ethnicity",
    //Body
    "Body Skin",
    "Skin Color",
    "Palm Color",
    "Skin Shine",
    "Body Hair",
    "Body Hair Color",
    "Corruption",
    "Corruption Wrinkles",
    "Body Muscles",
    "Muscle Mass",
    "Height (cm)",
    "Blood Color",
    "Blood Spill",
    // "Blood Metallic",
    // "Blood Glow",
    // "Footprint",
    // "Footprint Scale",
    //Head
    "Head",
    "Forehead Details",
    "Eyes Details",
    "Mouth Details",
    "Size",
    "Shape (Width/Depth)",
    "Neck (Width/Depth)",
    "Neck Length",
    //Hairs
    "Alt Shader",
    "Hair cut",
    "Shine",
    "Shine Intensity",
    "Details (Alt)",
    "Hairline",
    "Hair Color",
    "Hair Second Color",
    // "Hairline Color",
    "Strand Gradient",
    "Hair Gradient Position",
    "Hair Gradient Size",
    "Accessory Gradient Pos",
    "Accessory Gradient Size",
    //Facial Hairs
    "Facial Hair",
    "Facial Hair Variation",
    "Facial Hairline",
    "Facial Hair Color",
    //Skin Complexion
    "Head",
    "Head Opacity",
    "Body",
    "Body Opacity",
    "Hands",
    "Hands Opacity",
    //Wrinkles
    "Wrinkles",
    "Strength",
    //Scars
    "Face Scar",
    "Face Scar Age",
    "Body Scar",
    "Body Scar Age",
    //Sound
    "Voice",
    "Voice Pitch",
    // "Footstep",
    // "Cloth Foley",
    //Makeup
    "Makeup A",
    "Color A",
    "Gloss A",
    // "Metallic A",
    // "Glow A",
    "Makeup B",
    "Color B",
    "Gloss B",
    // "Metallic B",
    // "Glow B",
    "Makeup C",
    "Color C",
    "Gloss C",
    // "Metallic C",
    // "Glow C",
    //Warpaint
    "Head",
    "Body",
    "Hands",
    "Color",
    "Gloss",
    // "Metallic",
    // "Glow",
    "Details",
    //Upper Warpaint
    "Head",
    "Body",
    "Hands",
    "Color",
    "Gloss",
    // "Metallic",
    // "Glow",
    //Brows
    "Texture",
    "Brows Tracks Right",
    "Brows Tracks Left",
    "Color",
    "Depth",
    "Separation",
    "Outer Height",
    "Mid Height",
    "Inner Height",
    //Right Eye
    "Texture",
    "Iris Size",
    "Iris Color",
    "Glow",
    "Sectoral Shape",
    "Sectoral Color",
    "Sectoral Glow",
    "Pupil Size",
    "Pupil Color",
    "Pupil Glow",
    "Sclera Color",
    "Sclera Glow",
    "Veins",
    //Left Eye
    "Texture",
    "Iris Size",
    "Iris Color",
    "Glow",
    "Sectoral Shape",
    "Sectoral Color",
    "Sectoral Glow",
    "Pupil Size",
    "Pupil Color",
    "Pupil Glow",
    "Sclera Color",
    "Sclera Glow",
    "Veins",
    //Eyes
    "Size",
    "Angle",
    "Distance",
    "Height",
    "Depth",
    "Upper Eyelid",
    "Lower Eyelid",
    "Upper Eyelid Shape A",
    "Upper Eyelid Shape B",
    "Lower Eyelid Shape A",
    "Lower Eyelid Shape B",
    //Eyelashes
    "Color Top",
    "Color Bottom",
    "Density (Top/Bottom)",
    "Thickness (Top/Bottom)",
    "Length (Top/Bottom)",
    //Ears
    "Size",
    "Angle",
    "Twist",
    "Roll",
    //Cheeks
    "Height",
    "Width",
    "Fill",
    //Jaw
    "Chin Length",
    "Chin Width",
    "Width",
    "Jutting",
    //Nose
    "Tip Size",
    "Length",
    "Nose Height",
    "Nose Curve",
    "Nostril Width",
    //Mouth
    "Width",
    "Protrusion",
    "Lip Fullness",
    "Upper Lip Size",
    "Lower Lip Size",
    "Upper Lip Shape",
    "Lower Lip Shape",
    "Smile",
    //Torso
    "Chest (Width/Depth)",
    "Chest Length",
    "Belly (Width/Depth)",
    "Belly Length",
    "Lower Belly (Width/Depth)",
    "Lower Belly length",
    //Arms
    "Shoulder Width",
    "Shoulder Height",
    "Arms (Width/Depth)",
    "Forearms (Width/Depth)",
    "Hands (Width/Depth)",
    "Hands Length",
    //Legs
    "Pelvis (Width/Depth)",
    "Pelvis Length",
    "Leg separation",
    "Butt Separation",
    "Butt Height",
    "Thighs (Width/Depth)",
    "Calfs (Width/Depth)",
    "Feet Size",
    "Feet Length",
    "Feet Width",
    //Penis
    "Hide",
    "Hide Pubes",
    "Size",
    "Girth",
    "Glans",
    "Glans Size",
    "Testicle Size",
    "Testicle Sag",
    //Breasts
    "Size",
    "Height",
    "Separation",
    "Protrusion",
    "Rotation",
    "Perk",
    //Breasts Physics
    "Alpha",
    "Linear Spring",
    "Linear Damping",
    "Angular Spring",
    "Angular Damping",
    //Butt Physics
    "Alpha",
    "Linear Spring",
    "Linear Damping",
    "Angular Spring",
    "Angular Damping",
    //Aberrations
    "???",
    "???",
    "???",
    "???",
    "???",
    "???",
    "???",
    "???",
    "???",
    "???",
    "???",
    "???",
    "???",
    "???",
    "???",
    "???",
    "???",
    "???",
];

export const BODY_FIELDS_LENGTH = bodyFields.length;